'use strict';
function assert(ok,message){if(!ok){const e=new Error(message);e.status=422;throw e;}}
function context(user,tenantId,roles){assert(user&&user.id,'authenticated actor required');assert(tenantId,'x-tenant-id is required');if(user.tenantId||user.tenant_id)assert((user.tenantId||user.tenant_id)===tenantId,'tenant mismatch');const role=user.role||'member';assert(roles.includes(role),'role not authorized');return{tenantId,actorId:String(user.id),role};}
function validateBooking(input,resource){assert(/^[A-Za-z0-9._:-]{3,128}$/.test(input.idempotencyKey||''),'invalid idempotencyKey');const start=new Date(input.startsAt),end=new Date(input.endsAt);assert(Number.isFinite(start.getTime())&&Number.isFinite(end.getTime())&&end>start,'booking time range is invalid');assert(resource&&resource.active,'resource is unavailable');assert(Number.isInteger(input.attendees)&&input.attendees>0&&input.attendees<=resource.capacity,'attendee count exceeds capacity');return{...input,startsAt:start,endsAt:end};}
function overlaps(a,b){return new Date(a.startsAt)<new Date(b.endsAt)&&new Date(a.endsAt)>new Date(b.startsAt);}
function prorate({monthlyCents,activeDays,periodDays,adjustmentCents=0,taxBasisPoints=0}){for(const n of [monthlyCents,activeDays,periodDays,adjustmentCents,taxBasisPoints])assert(Number.isInteger(n),'billing values must be integers');assert(monthlyCents>=0&&activeDays>=0&&periodDays>0&&activeDays<=periodDays,'billing period is invalid');const subtotal=Math.round(monthlyCents*activeDays/periodDays);const taxable=subtotal+adjustmentCents;const tax=Math.round(Math.max(0,taxable)*taxBasisPoints/10000);return{subtotalCents:subtotal,adjustmentCents,taxCents:tax,totalCents:taxable+tax};}
function canGrantAccess({membership,validFrom,validUntil}){assert(membership&&membership.state==='active','active membership is required');assert(!membership.access_revoked_at,'membership access is revoked');const from=new Date(validFrom),until=new Date(validUntil);assert(until>from,'access validity is invalid');if(membership.ends_on)assert(until<=new Date(`${membership.ends_on}T23:59:59Z`),'access exceeds membership end');return true;}
function revokeGrant(grant,actor){assert(grant&&grant.status==='active','only active access can be revoked');assert(actor&&['site_admin','staff','admin'].includes(actor.role),'site staff authority is required');return{...grant,status:'revoked',revokedBy:String(actor.id)};}
module.exports={context,validateBooking,overlaps,prorate,canGrantAccess,revokeGrant};
